server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Auth Service Route
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        # Equipment Service Route
        - id: equipment-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/equipment/**

        # Sensor Service Route
        - id: sensor-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/sensors/**

        # Maintenance Service Route
        - id: maintenance-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/maintenance/**

        - id: spare-parts-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/spare-parts
          filters:
            - SetPath=/api/maintenance/spare-parts

        - id: error-codes-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/error-codes
          filters:
            - SetPath=/api/maintenance/error-codes

        - id: manuals-route
          uri: http://localhost:8084
          predicates:
            - Path=/api/manuals
          filters:
            - SetPath=/api/maintenance/manuals

        # Python AI Service (Predictive ML + SLM RAG)
        - id: ai-service
          uri: http://localhost:8000
          predicates:
            - Path=/api/ai/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 2
  instance:
    preferIpAddress: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expirationMs: 86400000
